---
- hosts: demo
  become: true
  tasks:
    - name: install httpd package
      yum: pkg=httpd state=latest
    - name: wait for service listening on port 80
      wait_for:
       path: /home/vmtutes/vinumaa.log
